### ISSUE TITLE
Remove 'Contact by Phone' checkbox on Profile page

### ISSUE THREAD

**Issue by v-stsier** [NewmanCatalysis/ITProCareerCenter#21]
Remove the 'Contact by Phone' checkbox on the Profile page.

Steps to reproduce
--------------------------
1. Sign in to the Career Center
2. Click Profile
3. Scroll down until you see the 'Phone Number' field
4. Directly below the 

phone number is a checkbox for 'Contact by Phone'

SUGGESTED BY: Ingrid Henkel

**Comment by NewmanCatalysis** [comment]
no repro
