### ISSUE TITLE
IT Pro Cloud Essentials form not populated

### ISSUE THREAD

**Issue by v-stsier** [NewmanCatalysis/ITProCareerCenter#23]
When logging in to the Cloud Essentials site from the Career Center and then claiming the 'free gift', user information is not prepopulated in the form.

Steps to reproduce
-------------------------
1. Sign in to the Career Center
2. Click 'Home'
3. Click 'Join now' under IT Pro Cloud Essentials
4. Swipe to 'Free Gift' on the hero banner
5. Click 'Claim gift'

Information should be pre-populated with existing MSA information.

From UAT feedback email
-----------------------------------
"IT Pro Cloud Essential Section – the form should be prepopulated since I already registered and was already forced to opt-in. [tc] hmmm… let me check this.  could be a bug PO"

SUGGESTED BY: Ingrid Henkel

**Comment by NewmanCatalysis** [comment]
No repro
