### ISSUE TITLE
Career Center remains signed in after sign out on Cloud Essentials

### ISSUE THREAD

**Issue by v-stsier** [NewmanCatalysis/ITProCareerCenter#24]
If a user signs out of Cloud Essentials, they appear to be signed out of Career Center even though they are still signed in.

Steps to reproduce
--------------------------
1. Make sure you are signed out of both Cloud Essentials and Career Center
2. Sign in to Career Center
3. Click 'Home'
4. In the IT Pro Cloud Essentials section, click 'Join now' 
5. Sign in to Cloud Essentials
6. Click 'Sign out'
7. Type in Career Center URL.  (Do not use browser back button)
8. You will be shown the Career Center sign in page - indicated that you are signed out.
9. Click 'Sign in'

You will be taken to your Career Center homepage without being asked for credentials

**Comment by NewmanCatalysis** [comment]
No repro
