### ISSUE TITLE
Sign out not working

### ISSUE THREAD

**Issue by v-stsier** [NewmanCatalysis/ITProCareerCenter#25]
Clicking 'Sign out' returns you to the Landing page but does not actually sign you out.

Steps to reproduce
--------------------------
Log in to the Career Center
Click 'Sign out' on any page
The landing page is displayed
Click 'Sign in'
The user home page is displayed

The user was never asked for credentials before being taken to their home page.

**Comment by NewmanCatalysis** [comment]
No repro
